# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name="Card's Name")),
                ('description', models.TextField(verbose_name='Description')),
                ('mana_cost', models.PositiveIntegerField(default=0, verbose_name='Mana Cost')),
                ('life', models.PositiveIntegerField(default=0, verbose_name='Life')),
                ('damage', models.PositiveIntegerField(default=0, verbose_name='Damage')),
                ('modified', models.PositiveIntegerField(null=True, verbose_name='Modified')),
            ],
        ),
        migrations.CreateModel(
            name='CardType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Type of Card')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='card_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.CardType', verbose_name='Type of Card'),
        ),
    ]
